[package]
name = "pheme-input"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
pheme-proto = { workspace = true }
pheme-core = { workspace = true }
crossbeam-channel = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
evdev = "0.13"
x11rb = { version = "0.14", features = ["xinput", "xtest", "xfixes", "randr"] }
wayland-client = "0.31"
ashpd = { workspace = true }
reis = { workspace = true }
futures-lite = { workspace = true }
async-channel = { workspace = true }

[target.'cfg(target_os = "windows")'.dependencies]
windows = { version = "0.62", features = [
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_System_LibraryLoader",
    "Win32_System_Threading",
    "Win32_UI_HiDpi",
    "Win32_UI_Input",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_WindowsAndMessaging",
] }
